name: 'Smart TODO Action'
description: 'Transforma comentários TODO/FIXME/BUG do código em GitHub Issues inteligentes.'
author: 'Diogo Ribeiro'

inputs:
  repo-token:
    required: true
    description: GitHub token to create issues

  report:
    required: false
    description: Whether to generate a TODO markdown report
    default: 'false'

  structured:
    required: false
    description: Use structured tag extraction with @assignee, #module, and key=value
    default: 'false'

  warn-overdue:
    required: false
    description: Emit warnings for TODOs with due dates in the past
    default: 'false'

  issue-title-template:
    required: false
    description: Optional path to custom issue title template

  issue-body-template:
    required: false
    description: Optional path to custom issue body template

  label-config:
    required: false
    description: Optional path to JSON file with custom label colors and descriptions

  llm:
    required: false
    description: Use LLM to generate issue titles and bodies
    default: 'false'

  openai-api-key:
    required: false
    description: 'OpenAI API key used when `llm` is true'

  openai-model:
    required: false
    description: OpenAI model to use (e.g., `gpt-3.5-turbo`, `gpt-4`)
    default: gpt-3.5-turbo

  sync-to-jira:
    required: false
    default: 'false'
    description: Enable Jira sync for created TODOs

  jira-api-token:
    required: false
    description: Jira API token or personal access token

  jira-base-url:
    required: false
    description: Base URL of your Jira instance (e.g. https://mycompany.atlassian.net)

  jira-email:
    required: false
    description: Email used in conjunction with the Jira API token

  limit:
    required: false
    description: Maximum number of issues to create
    default: '5'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'
  color: 'blue'
