name: 'Smart TODO Action'
description: 'Transforma comentários TODO/FIXME/BUG do código em GitHub Issues inteligentes.'
author: 'Diogo Ribeiro'

inputs:
  repo-token:
    required: true
    description: GitHub token to create issues
  report:
    required: false
    description: Whether to generate a TODO markdown report
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'
  color: 'blue'
