name: Smart TODO Action Example

on:
  push:
    branches: [main]

jobs:
  smart-todo:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn prepare
      - name: Run Smart TODO Action
        uses: DiogoRibeiro7/smart-todo-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
