name: Smart TODO Tracker

on:
  push:
    branches: [main]

jobs:
  smart-todo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: yarn install
      - run: yarn prepare

      - name: Run Smart TODO Action
        uses: ./
        with:
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          issue-title-template: src/templates/issueTitle.txt
          issue-body-template: src/templates/issueBody.md
          report: true

      - name: Upload TODO report
        uses: actions/upload-artifact@v3
        with:
          name: todo-report
          path: TODO_REPORT.md

      - name: Commit TODO report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add TODO_REPORT.md
          git commit -m "chore(report): update TODO report" || echo "No changes"
          git push
